// <auto-generated />
using System;
using BrewControl.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BrewControl.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260626181240_InicialCreate")]
    partial class InicialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BrewControl.Api.Models.Cerveja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estilo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cervejas");
                });

            modelBuilder.Entity("BrewControl.Api.Models.ParametrosFermentativos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CervejaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ExtratoPMaximo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ExtratoPMinimo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PhMaximo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PhMinimo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TemperaturaMaxima")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TemperaturaMinima")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CervejaId");

                    b.ToTable("ParametrosFermentativos");
                });

            modelBuilder.Entity("BrewControl.Api.Models.RegistroFermentativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CervejaId")
                        .HasColumnType("integer");

                    b.Property<int>("Classificacao")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Extrato")
                        .HasColumnType("numeric");

                    b.Property<string>("NumeroDeLote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<decimal>("Ph")
                        .HasColumnType("numeric");

                    b.Property<int>("TanqueId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Temperatura")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CervejaId");

                    b.HasIndex("TanqueId");

                    b.ToTable("RegistrosFermentativos");
                });

            modelBuilder.Entity("BrewControl.Api.Models.Tanque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Capacidade")
                        .HasColumnType("numeric");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tanques");
                });

            modelBuilder.Entity("BrewControl.Api.Models.ParametrosFermentativos", b =>
                {
                    b.HasOne("BrewControl.Api.Models.Cerveja", "Cerveja")
                        .WithMany()
                        .HasForeignKey("CervejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cerveja");
                });

            modelBuilder.Entity("BrewControl.Api.Models.RegistroFermentativo", b =>
                {
                    b.HasOne("BrewControl.Api.Models.Cerveja", "Cerveja")
                        .WithMany()
                        .HasForeignKey("CervejaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BrewControl.Api.Models.Tanque", "Tanque")
                        .WithMany()
                        .HasForeignKey("TanqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cerveja");

                    b.Navigation("Tanque");
                });
#pragma warning restore 612, 618
        }
    }
}
